import express, { Request, Response } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const port = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

// --- Phase 2: Dynamic Data Engine (Simulated Cloud Infrastructure) ---

// Simulated AWS Data Endpoint
app.get('/api/cloud/aws', (req: Request, res: Response) => {
  res.json({
    score: 84,
    resources: [
      { name: 'EC2 Instances', count: Math.floor(Math.random() * 200) + 50, risk: 'High', color: 'text-[#FF9900]' },
      { name: 'S3 Buckets', count: Math.floor(Math.random() * 50) + 10, risk: 'Medium', color: 'text-green-500' },
      { name: 'IAM Roles', count: Math.floor(Math.random() * 100) + 20, risk: 'Low', color: 'text-blue-400' },
      { name: 'RDS Databases', count: Math.floor(Math.random() * 30) + 5, risk: 'Medium', color: 'text-purple-500' },
      { name: 'VPCs', count: 12, risk: 'Low', color: 'text-cyan-500' },
      { name: 'Security Groups', count: Math.floor(Math.random() * 300) + 100, risk: 'Critical', color: 'text-red-500' }
    ],
    misconfigurations: [
      { id: `sg-${Math.floor(Math.random()*10000)}`, issue: 'SSH port 22 open to 0.0.0.0/0', severity: 'Critical' },
      { id: `s3-bucket-${Math.floor(Math.random()*10000)}`, issue: 'Bucket allows public read access', severity: 'High' },
      { id: `i-${Math.floor(Math.random()*10000)}`, issue: 'EC2 instance uses deprecated IMDSv1', severity: 'Medium' }
    ]
  });
});

// --- Phase 3: AI Assistant Integration (Grok / Fallback) ---
app.post('/api/chat', async (req: Request, res: Response): Promise<void> => {
  const { message, context } = req.body;
  const grokApiKey = process.env.GROK_API_KEY;

  if (!message) {
    res.status(400).json({ error: 'Message is required' });
    return;
  }

  // Define system prompt
  const systemPrompt = `You are Jarvis, the CloudGuardian AI Assistant. You are a highly advanced cybersecurity AI designed to analyze cloud environments (AWS, Azure, GCP). 
Context: ${JSON.stringify(context || 'No specific context provided.')}
Be concise, professional, and slightly futuristic in your responses. Highlight risks and provide mitigation commands.`;

  // Try to use real Grok API if key exists
  if (grokApiKey && grokApiKey !== 'your_grok_api_key_here') {
    try {
      const response = await fetch('https://api.x.ai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${grokApiKey}`
        },
        body: JSON.stringify({
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: message }
          ],
          model: 'grok-beta',
          stream: false,
          temperature: 0.7
        })
      });

      if (!response.ok) {
        throw new Error(`Grok API Error: ${response.statusText}`);
      }

      const data = await response.json();
      res.json({ 
        response: data.choices[0].message.content,
        isSimulated: false 
      });
      return;
    } catch (error) {
      console.error('Error calling Grok API, using fallback simulation:', error);
      // Fall through to simulation if API fails (e.g. rate limit, expired key)
    }
  }

  // Fallback Simulation Logic (if no key or API fails)
  setTimeout(() => {
    let aiResponse = "I have analyzed the request. ";
    
    const lowerMessage = message.toLowerCase();
    if (lowerMessage.includes('scan') || lowerMessage.includes('analyze')) {
      aiResponse += "Initiating deep neural scan of your cloud infrastructure... I detected 3 anomalies. An S3 bucket is exposed to the public, and an EC2 instance has port 22 open. I recommend applying a strict Security Group policy immediately.";
    } else if (lowerMessage.includes('fix') || lowerMessage.includes('mitigate')) {
      aiResponse += "To mitigate the exposed SSH port, execute the following CLI command:\n\n`aws ec2 revoke-security-group-ingress --group-id sg-12345 --protocol tcp --port 22 --cidr 0.0.0.0/0`\n\nWould you like me to automatically apply this patch?";
    } else if (lowerMessage.includes('hello') || lowerMessage.includes('hi')) {
      aiResponse = "Greetings, Commander. All systems are currently nominal. How can I assist you with your cloud security posture today?";
    } else {
      aiResponse += "Based on current telemetry, your environment requires attention. Please specify a resource ID for detailed threat analysis.";
    }

    res.json({ 
      response: aiResponse,
      isSimulated: true,
      note: 'This response was generated by the local simulation fallback because the Grok API key is missing or invalid.'
    });
  }, 1500); // 1.5s simulated delay
});

// Start Server
app.listen(port, () => {
  console.log(`CloudGuardian AI Backend running on http://localhost:${port}`);
  console.log(`Fallback Simulation Mode: ${!process.env.GROK_API_KEY || process.env.GROK_API_KEY === 'your_grok_api_key_here' ? 'ACTIVE' : 'INACTIVE'}`);
});
